[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Optional: keep or remove; either is fine with esbuild bundling.
  external_node_modules = ["@supabase/supabase-js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
